import os
import shutil
import datetime
import streamlit as st
from PIL import Image

# Import backend modules directly for cloud compatibility
from database import SessionLocal, PredictionRecord, init_db
from model_engine import analyze_image

# Initialize Database on Startup
init_db()

# Page Configuration
st.set_page_config(
    page_title="Advanced AI Medical Intelligence Platform",
    page_icon="🏥",
    layout="wide"
)

# Folder Setup
UPLOAD_DIR = "uploads"
OUTPUT_DIR = "outputs"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

def generate_llm_medical_report(prediction: str, confidence: float) -> str:
    return f"""
    === AUTOMATED CLINICAL ASSISTANT REPORT ===
    Diagnostic Classification : {prediction}
    Confidence Level         : {confidence:.2%}
    
    PRIMARY FINDINGS:
    - Deep Learning model analysis indicates visual features consistent with '{prediction}'.
    - Heatmap activation regions pinpoint high-density focal areas driving classification.
    
    CLINICAL RECOMMENDATIONS:
    - Review highlighted Grad-CAM focus regions alongside secondary symptom data.
    - Confirm diagnosis with standard laboratory panel and radiologist evaluation.
    
    DISCLAIMER:
    This report is generated by an automated Explainable AI model for decision support.
    It should not replace professional medical diagnosis.
    """.strip()

st.title("🏥 Advanced AI Medical Intelligence Platform")
st.markdown("### Explainable AI & LLM-Assisted Radiographic Diagnostic Suite")
st.markdown("---")

option = st.sidebar.radio("Navigation Menu", ["Diagnostic Workspace", "Prediction Audit Logs"])

if option == "Diagnostic Workspace":
    st.subheader("📤 Upload Radiographic Scan")
    uploaded_file = st.file_uploader("Select Chest X-Ray or Medical Scan...", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        col1, col2 = st.columns(2)

        image = Image.open(uploaded_file)
        with col1:
            st.image(image, caption="Original Input Scan", use_container_width=True)

        if st.sidebar.button("⚡ Run Diagnostic Analysis"):
            with st.spinner("Processing image through ResNet-18 Deep Learning & Grad-CAM Pipeline..."):
                try:
                    # Save input image locally
                    input_path = os.path.join(UPLOAD_DIR, uploaded_file.name)
                    with open(input_path, "wb") as f:
                        f.write(uploaded_file.getbuffer())

                    # Generate Grad-CAM output path
                    cam_output_path = os.path.join(OUTPUT_DIR, f"cam_{uploaded_file.name}")

                    # Execute deep learning & XAI inference directly
                    analysis = analyze_image(input_path, cam_output_path)
                    llm_report = generate_llm_medical_report(analysis["prediction"], analysis["confidence"])

                    # Save record to Database
                    db = SessionLocal()
                    record = PredictionRecord(
                        filename=uploaded_file.name,
                        prediction=analysis["prediction"],
                        confidence=analysis["confidence"],
                        cam_image_path=cam_output_path,
                        ai_report=llm_report
                    )
                    db.add(record)
                    db.commit()
                    db.close()

                    st.sidebar.success("Analysis Complete!")

                    # Render Results
                    with col2:
                        st.image(cam_output_path, caption="Explainable AI (Grad-CAM Heatmap)", use_container_width=True)

                    st.markdown("---")
                    st.subheader("📊 Diagnostic Summary & Confidence Metrics")

                    m1, m2 = st.columns(2)
                    m1.metric("Predicted Classification", analysis["prediction"])
                    m2.metric("Confidence Score", f"{analysis['confidence'] * 100:.2f}%")

                    st.markdown("---")
                    st.subheader("📝 Automated LLM Clinical Report")
                    st.info(llm_report)

                except Exception as e:
                    st.error(f"Error during analysis pipeline: {e}")

elif option == "Prediction Audit Logs":
    st.subheader("📜 Database History Logs")
    if st.button("Refresh History"):
        try:
            db = SessionLocal()
            records = db.query(PredictionRecord).order_by(PredictionRecord.id.desc()).all()
            
            if records:
                history_data = [
                    {
                        "ID": r.id,
                        "Filename": r.filename,
                        "Prediction": r.prediction,
                        "Confidence": f"{r.confidence * 100:.2f}%",
                        "Timestamp": str(r.timestamp)
                    }
                    for r in records
                ]
                st.dataframe(history_data, use_container_width=True)
            else:
                st.info("No prediction history found in database.")
            db.close()
        except Exception as e:
            st.error(f"Database query error: {e}")