from fastapi import FastAPI, UploadFile, File, Depends, HTTPException
from fastapi.staticfiles import StaticFiles
from sqlalchemy.orm import Session
import os
import shutil

from database import get_db, PredictionRecord
from model_engine import analyze_image

app = FastAPI(
    title="Advanced AI Medical Intelligence Platform API",
    version="1.0.0"
)

# Folder setup
UPLOAD_DIR = "uploads"
OUTPUT_DIR = "outputs"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Mount static folder so images can be served over URL
app.mount("/outputs", StaticFiles(directory="outputs"), name="outputs")

def generate_llm_medical_report(prediction: str, confidence: float) -> str:
    return f"""
    === AUTOMATED CLINICAL ASSISTANT REPORT ===
    Diagnostic Classification : {prediction}
    Confidence Level         : {confidence:.2%}
    
    PRIMARY FINDINGS:
    - Deep Learning model analysis indicates visual features consistent with '{prediction}'.
    - Heatmap activation regions pinpoint high-density focal areas driving classification.
    
    CLINICAL RECOMMENDATIONS:
    - Review highlighted Grad-CAM focus regions alongside secondary symptom data.
    - Confirm diagnosis with standard laboratory panel and radiologist evaluation.
    
    DISCLAIMER:
    This report is generated by an automated Explainable AI model for decision support.
    It should not replace professional medical diagnosis.
    """.strip()

@app.get("/")
def read_root():
    return {"status": "Active", "system": "AI Medical Intelligence Engine"}

@app.post("/predict")
async def predict_medical_image(
    file: UploadFile = File(...), 
    db: Session = Depends(get_db)
):
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Uploaded file must be an image.")

    input_path = os.path.join(UPLOAD_DIR, file.filename)
    with open(input_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    cam_output_path = os.path.join(OUTPUT_DIR, f"cam_{file.filename}")

    analysis = analyze_image(input_path, cam_output_path)
    llm_report = generate_llm_medical_report(analysis["prediction"], analysis["confidence"])

    record = PredictionRecord(
        filename=file.filename,
        prediction=analysis["prediction"],
        confidence=analysis["confidence"],
        cam_image_path=cam_output_path,
        ai_report=llm_report
    )
    db.add(record)
    db.commit()
    db.refresh(record)

    return {
        "id": record.id,
        "filename": record.filename,
        "prediction": record.prediction,
        "confidence": record.confidence,
        "cam_image_path": record.cam_image_path,
        "report": record.ai_report,
        "timestamp": str(record.timestamp)
    }

@app.get("/history")
def get_prediction_history(db: Session = Depends(get_db)):
    records = db.query(PredictionRecord).order_by(PredictionRecord.id.desc()).all()
    return records